# Classification Case Study

### Import libraries 

In [70]:
# Importing required packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style='white')

## Load data from final csv

In [71]:
train = pd.read_csv("final_train.csv")

In [72]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Gender          564 non-null    object 
 1   Married         564 non-null    object 
 2   Dependents      564 non-null    int64  
 3   Education       564 non-null    object 
 4   SelfEmployed    564 non-null    object 
 5   LoanAmountTerm  564 non-null    float64
 6   CreditHistory   564 non-null    float64
 7   PropertyArea    564 non-null    object 
 8   LoanStatus      564 non-null    int64  
 9   LoanAmountLog   564 non-null    float64
 10  IncomeLog       564 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 48.6+ KB


In [73]:
X = train.drop(columns=['LoanStatus'])
y = train.LoanStatus

In [74]:
X = pd.get_dummies(X)  # One Hot Encoding 

In [75]:
X.columns

Index(['Dependents', 'LoanAmountTerm', 'CreditHistory', 'LoanAmountLog',
       'IncomeLog', 'Gender_Female', 'Gender_Male', 'Married_No',
       'Married_Yes', 'Education_Graduate', 'Education_Not Graduate',
       'SelfEmployed_No', 'SelfEmployed_Yes', 'PropertyArea_Rural',
       'PropertyArea_Semiurban', 'PropertyArea_Urban'],
      dtype='object')

In [76]:
X.sample(5)

Dependents  LoanAmountTerm  CreditHistory  LoanAmountLog  IncomeLog  \
558           0           360.0            1.0       4.682131   8.552946   
314           0           360.0            1.0       3.828641   7.774015   
402           0           240.0            1.0       4.844187   9.215029   
419           2           360.0            1.0       4.564348   8.258163   
390           1           360.0            0.0       4.700480   9.095715   

     Gender_Female  Gender_Male  Married_No  Married_Yes  Education_Graduate  \
558              0            1           0            1                   1   
314              1            0           1            0                   1   
402              1            0           0            1                   1   
419              0            1           0            1                   1   
390              0            1           0            1                   1   

     Education_Not Graduate  SelfEmployed_No  SelfEmployed_Yes  \
558                       0                1                 0   
314                       0                1                 0   
402                       0                1                 0   
419                       0                1                 0   
390                       0                1                 0   

     PropertyArea_Rural  PropertyArea_Semiurban  PropertyArea_Urban  
558                   1                       0                   0  
314                   1                       0                   0  
402                   0                       1                   0  
419                   0                       1                   0  
390                   0                       0                   1

In [77]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Dependents              564 non-null    int64  
 1   LoanAmountTerm          564 non-null    float64
 2   CreditHistory           564 non-null    float64
 3   LoanAmountLog           564 non-null    float64
 4   IncomeLog               564 non-null    float64
 5   Gender_Female           564 non-null    uint8  
 6   Gender_Male             564 non-null    uint8  
 7   Married_No              564 non-null    uint8  
 8   Married_Yes             564 non-null    uint8  
 9   Education_Graduate      564 non-null    uint8  
 10  Education_Not Graduate  564 non-null    uint8  
 11  SelfEmployed_No         564 non-null    uint8  
 12  SelfEmployed_Yes        564 non-null    uint8  
 13  PropertyArea_Rural      564 non-null    uint8  
 14  PropertyArea_Semiurban  564 non-null    ui

In [78]:
X.shape

(564, 16)

### Split data into train and test data 

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [80]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [81]:
def print_scores(y_true, y_pred):
    cm = confusion_matrix(y_true,y_pred)
    tn = cm[0,0]
    tp = cm[1,1]
    fp = cm[0,1]
    fn = cm[1,0]
    print(f"Overall Accuracy                      : {(tp + tn) / (tp + fp + tn + fn):.2f}")
    print(f"Precision of Positive cases           : {tp / (tp + fp):.2f}")
    print(f"Precision of Negative cases           : {tn / (tn + fn):.2f}")
    print(f"Positive Recall or TPR or Sensitivity : {tp / (tp + fn):.2f}")
    print(f"Negative Recall or TNR or Specificity : {tn / (tn + fp):.2f}")      

## Logistic Regression

In [82]:
# Importing packages logistic regression and evaluation 
from sklearn.linear_model import LogisticRegression

In [83]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)

StandardScaler()

In [84]:
X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

In [85]:
# logistic regression   
model = LogisticRegression()
model.fit(X_train_scaled,y_train)

LogisticRegression()

In [86]:
# Check model's performance with train data 
model.score(X_train_scaled,y_train)

0.8248337028824834

In [87]:
y_pred = model.predict(X_test_scaled)

In [88]:
accuracy_score(y_test,y_pred)

0.7787610619469026

In [89]:
confusion_matrix(y_test,y_pred)

array([[13, 22],
       [ 3, 75]], dtype=int64)

In [90]:
print_scores(y_test,y_pred)

Overall Accuracy                      : 0.78
Precision of Positive cases           : 0.77
Precision of Negative cases           : 0.81
Positive Recall or TPR or Sensitivity : 0.96
Negative Recall or TNR or Specificity : 0.37


### Display classification report

In [91]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.37      0.51        35
           1       0.77      0.96      0.86        78

    accuracy                           0.78       113
   macro avg       0.79      0.67      0.68       113
weighted avg       0.79      0.78      0.75       113



In [92]:
model.coef_

array([[ 0.12504115, -0.06339225,  1.52887566, -0.07144193,  0.01978037,
        -0.04273509,  0.04273509, -0.08791328,  0.08791328,  0.04988399,
        -0.04988399, -0.01659069,  0.01659069, -0.14173176,  0.21747696,
        -0.08953919]])

In [93]:
y_pred_prob = model.predict_proba(X_test_scaled)

In [94]:
y_pred_prob[5:10], y_pred[5:10]

(array([[0.18926033, 0.81073967],
        [0.93918012, 0.06081988],
        [0.16626366, 0.83373634],
        [0.19272632, 0.80727368],
        [0.35005484, 0.64994516]]),
 array([1, 0, 1, 1, 1], dtype=int64))

## Decision Tree

In [95]:
from sklearn.tree import DecisionTreeClassifier

In [96]:
model = DecisionTreeClassifier(max_depth=5)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [97]:
model.score(X_train,y_train)

0.8536585365853658

In [98]:
y_train_pred = model.predict(X_train)

In [99]:
print_scores(y_train,y_train_pred)

Overall Accuracy                      : 0.85
Precision of Positive cases           : 0.83
Precision of Negative cases           : 0.95
Positive Recall or TPR or Sensitivity : 0.99
Negative Recall or TNR or Specificity : 0.57


In [100]:
y_pred = model.predict(X_test)

In [101]:
print_scores(y_test,y_pred)

Overall Accuracy                      : 0.79
Precision of Positive cases           : 0.79
Precision of Negative cases           : 0.79
Positive Recall or TPR or Sensitivity : 0.95
Negative Recall or TNR or Specificity : 0.43


In [102]:
confusion_matrix(y_test,y_pred)

array([[15, 20],
       [ 4, 74]], dtype=int64)

In [103]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.43      0.56        35
           1       0.79      0.95      0.86        78

    accuracy                           0.79       113
   macro avg       0.79      0.69      0.71       113
weighted avg       0.79      0.79      0.77       113



### Decision Tree Created by Classifier

In [104]:
# Print tree generated by DecisionTreeClassifier
from sklearn.tree import export_text
tree_rules = export_text(model, feature_names=list(X_train))
print(tree_rules)

|--- CreditHistory <= 0.50
|   |--- LoanAmountLog <= 6.30
|   |   |--- LoanAmountLog <= 4.86
|   |   |   |--- class: 0
|   |   |--- LoanAmountLog >  4.86
|   |   |   |--- LoanAmountLog <= 4.88
|   |   |   |   |--- class: 1
|   |   |   |--- LoanAmountLog >  4.88
|   |   |   |   |--- PropertyArea_Semiurban <= 0.50
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- PropertyArea_Semiurban >  0.50
|   |   |   |   |   |--- class: 0
|   |--- LoanAmountLog >  6.30
|   |   |--- class: 1
|--- CreditHistory >  0.50
|   |--- IncomeLog <= 9.90
|   |   |--- IncomeLog <= 7.78
|   |   |   |--- PropertyArea_Semiurban <= 0.50
|   |   |   |   |--- Gender_Female <= 0.50
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- Gender_Female >  0.50
|   |   |   |   |   |--- class: 0
|   |   |   |--- PropertyArea_Semiurban >  0.50
|   |   |   |   |--- class: 1
|   |   |--- IncomeLog >  7.78
|   |   |   |--- LoanAmountTerm <= 48.00
|   |   |   |   |--- class: 0
|   |   |   |--- LoanAmountTerm >  48.00
|   |

## KNN 

In [105]:
from sklearn.neighbors import KNeighborsClassifier

In [106]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [107]:
y_train_pred = model.predict(X_train_scaled)

In [108]:
print_scores(y_train,y_train_pred)

Overall Accuracy                      : 0.82
Precision of Positive cases           : 0.80
Precision of Negative cases           : 0.89
Positive Recall or TPR or Sensitivity : 0.97
Negative Recall or TNR or Specificity : 0.49


In [109]:
y_pred = model.predict(X_test_scaled)

In [110]:
print_scores(y_test,y_pred)

Overall Accuracy                      : 0.75
Precision of Positive cases           : 0.76
Precision of Negative cases           : 0.71
Positive Recall or TPR or Sensitivity : 0.94
Negative Recall or TNR or Specificity : 0.34


## Naive Bayes 

In [111]:
from sklearn.naive_bayes import GaussianNB

In [112]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [113]:
y_train_pred = model.predict(X_train)

In [114]:
print_scores(y_train,y_train_pred)

Overall Accuracy                      : 0.82
Precision of Positive cases           : 0.80
Precision of Negative cases           : 0.89
Positive Recall or TPR or Sensitivity : 0.97
Negative Recall or TNR or Specificity : 0.49


In [115]:
y_pred = model.predict(X_test)

In [116]:
print_scores(y_test,y_pred)

Overall Accuracy                      : 0.79
Precision of Positive cases           : 0.79
Precision of Negative cases           : 0.79
Positive Recall or TPR or Sensitivity : 0.95
Negative Recall or TNR or Specificity : 0.43


## Support Vector Machines

In [117]:
from sklearn.svm import SVC

In [118]:
model = SVC()
model.fit(X_train_scaled,y_train)

SVC()

In [119]:
y_train_pred = model.predict(X_train_scaled)

In [120]:
print_scores(y_train,y_train_pred)

Overall Accuracy                      : 0.83
Precision of Positive cases           : 0.81
Precision of Negative cases           : 0.96
Positive Recall or TPR or Sensitivity : 0.99
Negative Recall or TNR or Specificity : 0.50


In [121]:
y_pred = model.predict(X_test_scaled)

In [122]:
print_scores(y_test,y_pred)

Overall Accuracy                      : 0.78
Precision of Positive cases           : 0.77
Precision of Negative cases           : 0.81
Positive Recall or TPR or Sensitivity : 0.96
Negative Recall or TNR or Specificity : 0.37
